Check type before taking substring. Hotfix for #41.
Typescript understandably complains at compile time:
```
src/CPUMonitor.ts(23,21): error TS2339: Property 'join' does not exist on type 'never'.
```
but it works for now.